@startuml
component "Assertions Framework APIs" as api {
    component "JSON Schema validator" as v1
    component "Rego validator" as v2
    component "CQL2-text filter validator" as v3
    
    v1 -[hidden]- v2
    v2 -[hidden]- v3
}

component "Assertions Framework CLI" as cli
component "CWL2OGC" as cto
component "CWL Utils" as cwlu

cli -u-> api
cli -d-> cto
cli -d-> cwlu

component "Execution MATE API" as exec
component "FastAPI" as fastapi
component "FastAPI Dependency" as dep

exec -l-> api
exec -d-> fastapi
fastapi -r-> dep

@enduml
